### PR TITLE
add pride titles

### PR DESCRIPTION
**Pull request by themoonisacheese**
This is also part of the same file @Aproxia-dev and I shared 2 years ago. this i'm pretty sure is all her work.

i'm making this a separated PR because it's not the same feel as the rythm game titles, but i'd still love for everyone to see pride titles, so i'd get if you would want one and not the other.

screenshots:
Be gay do crimes (rainbow flag)

Trans rights are human rights (trans flag)

Be bi make people cri (bi flag)

Hearts not parts (pan flag)

### CODE REVIEW

**Comment by emifloofy** [comment]
wowie that was a while ago haha

**Comment by RedBrumbler** [comment]
my one feedback is that some of these are so big they go behind the menu, which can make it harder to read the menu, if possible I'd recommend making them at most 3 lines long or something

not that I have any say in this

**Comment by Saeraphinx** [comment]
as much as i agree with it and see why its 5 lines, i agree with red that it does feel a little too big. not a huge deal tho imo. otherwise lgtm

**Comment by themoonisacheese** [comment]
From regular use it's not a problem at all, since the newer menus are all opaque. There are some menus that are transparent in mods (such as the one in these screenshots) but in general it's never bothered me once. also consider that these screenshots are taken in fpfc mode, which is like 1m50 off the ground.

**Comment by Saeraphinx** [comment]
i forgot
also be gay do crime

**Pull request merged**
